## preamble

### setup

```{r load-libs, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(scran)
library(scater)
library(ggplot2)
library(tidytext)
library(patchwork)
library(BiocParallel)
bp <- MulticoreParam(30)
source("utils.R")
set.seed(250310)
```

### loading

```{r load-data}
rds <- list.files("../outs", pat <- "^sub-(.*)\\.rds", full.names=TRUE)
names(sub) <- sub <- gsub(pat, "\\1", basename(rds))
lys <- setNames(lapply(rds, readRDS), sub)
sapply(lys, ncol)
```

## labelling

```{r lab}
imm <- c(
    a="Th", d="Tc", f=NA,
    b="Bn", j="Bm",
    c="mast",  
    g="macro1",
    h="cDC2_CCR7",
    k="cDC1",
    l=NA,
    m=NA,
    r="macro2",
    e="PC_IgA1", m="PC_IgA1",
    i="PC_IgA2", n="PC_IgA2",
    p="PC_IgG", s="PC_IgG",
    o="PC_IgM", q="PC_IgM",
    t="nphil")
setdiff(unique(lys$imm$kid), names(imm)) 
str <- c(
    a="fib_ADAM", 
    b="LEC",
    c="SMC",
    d="fib_NR4A1",
    e="fib_PI16",
    f="SMC",
    g=NA,
    h="CAF_NOTCH3",
    i="CAF_F3",
    j="BEC",
    k="fib.TLS",
    l="BEC",
    m=NA,
    n="BEC",
    o="fib_PDGFRA",
    p="fib",
    q="CAF_CTHRC1",
    r="IAF_MMP")
setdiff(unique(lys$str$kid), names(str))
epi <- c(
    a="epi.goblet", 
    b="epi_MUC5AC",
    c="epi_MSLN",
    d=NA,
    e="epi.EE",
    f="epi.entero",
    g="epi.1",
    h="epi.2",
    i="epi.3",
    j="epi.paneth-like",
    k="epi_KLK10/CLDN2",
    l="epi_LGR5",
    m="epi_MUC5AC",
    n="epi.4",
    o="epi_LEFTY1",
    p="epi.stress",
    q="epi_DNMT1",
    r="epi_REG/DUOX")
setdiff(unique(lys$epi$kid), names(epi))

lab <- list(epi=epi, imm=imm, str=str)
for (. in sub) {
    idx <- match(lys[[.]]$kid, names(lab[[.]]))
    lys[[.]]$lv2 <- factor(lab[[.]][idx], sort(unique(lab[[.]])))
}
# fqs <- lapply(lys, \(.) prop.table(table(.$pid, .$lv2)))
# lapply(fqs, \(.) round(100*prop.table(., 1)))
# lapply(lys, \(.) round(100*prop.table(., 2)))
lapply(lys, \(.) table(.$lv2))
sapply(lys, \(.) nlevels(.$lv2))
```

## plotting

### compositions

::: {.panel-tabset}

```{r plt-fqs, results="asis", fig.width=4, fig.height=2}
for (. in names(lys)) {
    p <- .plt_fq(lys[[.]], x="lv2", y="sid", id=., pal=.pal)
    cat("#### ", ., "\n"); print(p); cat("\n\n")
}
```

:::

### reduction

::: {.panel-tabset}

```{r plt-map, results="asis", fig.width=15, fig.height=5}
ids <- c("run", "sid", "lv2")
for (. in sub) {
    p <- .plt_dr(lys[[.]], ids) & ggtitle(.lab(., ncol(lys[[.]])))
    cat("#### ", ., "\n"); print(p); cat("\n\n")
}
```

:::

## markers

```{r mgs-sel}
gs <- list(
    imm=list(
        Bm=c("BCL7A", "CR2", "CD19", "CD40", "CD69", "CD79A", "CD83", "CIITA", "SELL", "IGHD"),
        Bn=c("BANK1", "MS4A1"),
        Ba=c("BIRC5"),
        PC_IgA=c("MZB1", "XBP1", "IGHA1", "IGHA2"),
        PC_IgG=c("IGHG1"), 
        PC_IgM=c("IGHM"),
        Th=c("CD2", "CD3D", "CD4", "ICOS", "CCR4"),
        Tc=c("CD8A", "GZMA", "GZMK", "NKG7"),
        Tp=c("MKI67", "TOP2A"),
        mast=c("KIT", "IL1RL1"),
        cDC2_CCR7=c("CCR7"),
        cDC1=c("LAMP3", "CLEC10A", "ITGAX"),
        nphil=c("IL1B", "S100A8", "S100A9", "MMP9"),
        TRM=c("CD14", "CD68", "CD163", "APOE", "APOC1", "CTSD", "C1QA", "C1QB", "C1QC")
    ),
    epi=list(
        epi.EE=c(
            c("BEST4", "CA7", "OTOP2", "CTFR", "CA1", "GPT", "MUC17", "TFF1",
        "CD55", "TM4SF1", "DUOX2", "DUOXA1", "APOA1",
        "CHGA", "PCSK1N", "SCT", "SCGN", "NEUROD1", "SOX4",  
        "FCGBP", "ZG16", "SLC26A3", "AQP8", "CEACAM7", "LGR5",
        "RGMB", "ASCL2", "OLFM4", "PCLAF", "PCNA", 
        "SH2D6", "LRMP", "MATK", "FYB1", "HPGDS", "MUC6", "PGC", "AQP5", "BPIFB1"),
            "CHGA", "CHGB", "ENPP2", "SST", "PYY"),
        epi.goblet=c("TFF3", "MUC2", "MUC5AC"),
        epi.entero=c("FABP1", "FABP2", "ALDOB", "SLC26A2", "CA1", "CA4", "CA7", "KRT19", "KRT20"),
        epi.stress=c("DUOX2", "DUOXA2", "CTSE", "KLK10"),
        `epi.goblet-progen`=c("REG4"),
        epi.stem=c("OLFM4", "KCNQ1"),
        epi.prolif=c("MKI67", "TOP2A", "DNMT1"),
        epi.stem_LGR5.1=c("NOTUM", "AXIN2", "ZBTB4", "MCTP1", "ASCL2", "LGR5"),
        epi.stem_LGR5.2=c("CLDN2", "ODAM", "CCL15", "GHR"),
        epi.4=c("TMEM63C"),
        `epi.paneth-like`=c("REG1A", "REG1B", "REG3A", "DEFA5", "DEFA6"),
        epi.1=c("MMP7", "KRT23", "KRT17", "KRT80"),
        epi.6=c("DMXL2", "TUSC3"),
        epi.2=c("TSLP", "ESPN", "ALPI", "ATP12A"),
        epi.3=c("C3", "CISH"),
        epi.5=c("SPARC", "CALD1")
    ),
    str=list(
        SMC=c("MYL9", "MYLK", "MYH11", "ACTA2", "TAGLN"),
        BEC=c("CDH5", "FLT1", "CLDN5"),
        LEC=c("PECAM1", "VWF", "CD34", "CD93", "EGFL7", "KLF2", "LYVE1", "PROX1", "CCL21"),
        fib=c("PTGIS", "SFRP1", "SFRP2", "PI16"),
        fib_TLS=c("C3", "CLU", "LTA3", "CCL19", "CXCL13", "SPIB"),
        IAF_MMP=c("MMP1", "MMP3", "MMP10", "MMP19", "CXCL5", "CXCL8", "SMOX", "ASRGL1"),
        fib_ADAMDEC1=c("ADAMDEC1", "ADAM28", "BMP5", "FGFR4", "CCL11"),
        CAF_L1CAM=c("L1CAM", "ITGB8", "CCBE1"),
        CAF_CXCL14=c("COL4A5", "CXCL14", "F3", "PDGFRA"),
        CAF_CTHRC1=c("CTHRC1", "FN1", "COL10A1", "FAP"),
        CAF_COL4=c("PDGFA", "COL4", "COL5A3", "LZTS1")
    )
)
```

::: {.panel-tabset}

```{r plt-mgs-sel, results="asis", fig.width=15, fig.height=4}
ps <- lapply(sub, \(.) {
    .gs <- unique(unlist(gs[[.]]))
    .gs <- intersect(.gs, rownames(lys[[.]]))
    mtx <- logcounts(lys[[.]])[.gs, ]
    .plt_hm(lys[[.]], mtx, by="lv2", id=.) + 
        coord_flip(expand=FALSE) + theme(
            axis.text.y=element_text(size=12), 
            axis.text.x=element_text(size=8, angle=90, hjust=1, vjust=0.5))
})
for (. in sub) { cat("### ", ., "\n"); print(ps[[.]]); cat("\n\n") }
```

:::

## profiles

### selection

```{r mgs}
mgs <- lapply(lys, \(sub) findMarkers(
    sub, groups=sub$lv2, block=sub$pid, 
    direction="up", add.summary=TRUE, BPPARAM=bp))
```

```{r}
sel <- lapply(sub, \(.) {
    ns <- sapply(mgs[[.]], \(df) {
        gs <- rownames(lys[[.]])
        top <- rownames(df)[df$Top <= 200]
        setNames(gs %in% top, gs)
    }) |> rowSums()
    names(which(ns > 1))
})
sel <- lapply(sel, \(.) unique(unlist(.)))
sapply(sel, length)
```

```{r plt-upset, fig.width=4, fig.height=2.5}
UpSetR::upset(mtx <- UpSetR::fromList(sel))
```

### aggregation

```{r pbs}
pbs <- lapply(lys, \(sce) {
    ids <- colData(sce)[c("pid", kid <- "lv2")]
    pbs <- aggregateAcrossCells(sce, ids, BPPARAM=bp)
    sizeFactors(pbs) <- NULL
    pbs <- logNormCounts(pbs, log=FALSE)
    aggregateAcrossCells(pbs, pbs[[kid]], BPPARAM=bp,
        statistics="mean", use.assay.type="normcounts")
})
```

## appendix

### saving

```{r save-data}
for (. in sub) {
    rds <- sprintf("../outs/pbs-lv2,%s.rds", .)
    if (!file.exists(rds)) {
        mtx <- assay(pbs[[.]])[sel[[.]], ]
        saveRDS(mtx, rds)
    }
}
```

::: {.callout-note icon=false, collapse=true}

### session

```{r session-info}
#| code-fold: false
sessionInfo()
```

:::